### ISSUE TITLE
we cannot change the name

### ISSUE THREAD

**Issue by maliaoshui** [PassionPenguin/RailMapMaker#6]
> why does station name cannot change?

**Comment by PassionPenguin** [comment]
sorry, but it can be changed in station editor panel in fact... Just click the right-bottom of the screen and you will find 'station', inside the panel you can select the station and you will be able to change all the station's information

**Comment by PassionPenguin** [comment]
Wondering if you have any question? 
Have a nice day in the application~:)

**Comment by PassionPenguin** [comment]
<img width="1680" alt="截屏2020-05-07 下午10 15 35" src="https://user-images.githubusercontent.com/41184947/81305014-69afe380-90b0-11ea-9111-4ce394c21c98.png">

That's the panels which are designed for editing stations' information
